### ISSUE TITLE
Hex Editor Bug

### ISSUE THREAD

**Issue by PaduraruCristian** [meemknight/pavo#5]
When displaying an address close to 2^64 - 1, the address on the left side overflows which leads to committed areas being shown as uncommitted.

**Comment by meemknight** [comment]
cred ca putem sa facem un clamp la value sau ceva

**Comment by meemknight** [comment]
ok am verificat e deja clamped

**Comment by meemknight** [comment]
ok am rezolvat
https://github.com/meemknight/pavo/blob/313445f438cd1c54a7dd3db78fde2faaa478f4c5/pavo-gui/src/gameLayer/hexEditor.cpp#L288
